'use client';

import { useState } from 'react';
import { 
  Download, 
  CheckCircle2, 
  History, 
  FileEdit, 
  MinusCircle, 
  AlertTriangle, 
  FileText, 
  Scale, 
  ArrowRight, 
  Sparkles
} from 'lucide-react';
import { Disclaimer } from '@/components/Disclaimer';
import { DocumentType, OutputLanguage, DOCUMENT_TYPES, DOCUMENT_TYPE_LABELS, OUTPUT_LANGUAGES, LANGUAGE_LABELS } from '@/lib/config';
import { USER_ERROR_MESSAGES } from '@/lib/errors';
import { CompareResponse } from '@/lib/schemas/compare';

export default function ComparePage() {
  const [activeTab, setActiveTab] = useState<'redline' | 'custom'>('redline');
  const [accepted, setAccepted] = useState(false);
  const [counterProposed, setCounterProposed] = useState(false);
  const [copiedNotification, setCopiedNotification] = useState<string | null>(null);

  // Custom comparison state
  const [docType, setDocType] = useState<DocumentType>('rental');
  const [language, setLanguage] = useState<OutputLanguage>('en');
  const [docAText, setDocAText] = useState('');
  const [docBText, setDocBText] = useState('');
  const [customResult, setCustomResult] = useState<CompareResponse | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [customError, setCustomError] = useState<string | null>(null);

  const handleExportRedline = () => {
    const content = `LEGAL LENS REDLINE COMPARISON REPORT
Matter: #ARB-2024-918
Parties: Alpha Vendor Corp vs. Zenith Global Logistics
Date: ${new Date().toLocaleDateString()}

==================================================
SUMMARY OF CRITICAL DIVERGENCES
==================================================

1. CLAUSE 8 • PAYMENT TERMS [HIGH IMPACT]
- Original: Net 30 business days from receipt date
- Proposed Counter-Draft: Net 90 calendar days from milestone verification
- Risk Delta: Extended by 60 days, slowing operational cash flow.
- Recommendation: Reject extension. Propose Net 45.

2. CLAUSE 12 • JURISDICTION [MEDIUM IMPACT]
- Original: Singapore International Arbitration Centre (SIAC) - 3 arbitrators
- Proposed Counter-Draft: Domestic Arbitration in Mumbai, India under 1996 Act
- Risk Delta: Replaces neutral international seat with domestic framework.
- Recommendation: Counter seat (e.g., Delhi High Court or neutral hybrid).

3. SECTION 19 • FORCE MAJEURE [LOW IMPACT]
- Original: Standard Acts of God, flood, war, civil commotion.
- Proposed Counter-Draft: Expands to include regulatory shutdowns & sovereign embargoes.

Generated by Legal Lens AI Judicial Dossier.
`;
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'Redline-ARB-2024-918.txt';
    a.click();
    URL.revokeObjectURL(url);
    showToast('Redline report exported successfully.');
  };

  const showToast = (msg: string) => {
    setCopiedNotification(msg);
    setTimeout(() => setCopiedNotification(null), 3000);
  };

  const handleCustomCompare = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!docAText.trim() || !docBText.trim()) {
      setCustomError('Please provide text for both Document A and Document B.');
      return;
    }

    setCustomError(null);
    setIsLoading(true);
    setCustomResult(null);

    try {
      const response = await fetch('/api/compare', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          textA: docAText.trim(),
          textB: docBText.trim(),
          docType,
          language,
        }),
      });

      const data = (await response.json()) as CompareResponse & {
        error?: { code: string; message: string };
      };

      if (!response.ok || data.error) {
        const code = data.error?.code ?? 'INTERNAL_ERROR';
        setCustomError(
          USER_ERROR_MESSAGES[code as keyof typeof USER_ERROR_MESSAGES] ?? 'Comparison failed.',
        );
        return;
      }

      setCustomResult(data);
    } catch {
      setCustomError('Comparison failed. Please check your network connection.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="w-full bg-[#F8FAFC] min-h-screen dark:bg-slate-950 text-slate-900 dark:text-slate-100 pb-16">
      {/* Toast Notification */}
      {copiedNotification && (
        <div className="fixed bottom-6 right-6 z-50 rounded-xl bg-slate-900 px-4 py-3 text-xs font-semibold text-white shadow-xl animate-in fade-in slide-in-from-bottom-2 dark:bg-slate-100 dark:text-slate-900 flex items-center gap-2">
          <CheckCircle2 className="h-4 w-4 text-emerald-400 dark:text-emerald-600" />
          <span>{copiedNotification}</span>
        </div>
      )}

      <main className="mx-auto w-full max-w-6xl px-4 py-8 sm:px-8 sm:py-10 flex flex-col gap-8">
        {/* Matter Code Pill & Top Header Row */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex flex-col gap-1.5">
            <div className="inline-flex items-center gap-1.5 self-start px-2.5 py-0.5 rounded-full bg-blue-50 border border-blue-100 text-blue-700 text-xs font-semibold dark:bg-blue-950/60 dark:border-blue-900 dark:text-blue-300">
              <span>Matter #ARB-2024-918</span>
            </div>
            <h1 className="text-3xl font-extrabold tracking-tight text-slate-900 dark:text-white font-serif">
              Compare Versions
            </h1>
            <p className="text-sm text-slate-500 dark:text-slate-400">
              Review key revisions between Original and Counter-Draft
            </p>
          </div>

          {/* Action Buttons */}
          <div className="flex items-center gap-3">
            <button
              type="button"
              onClick={handleExportRedline}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-slate-200 bg-white hover:bg-slate-50 text-slate-700 text-xs font-semibold shadow-2xs transition-all dark:border-slate-800 dark:bg-slate-900 dark:text-slate-200 dark:hover:bg-slate-800 cursor-pointer"
            >
              <Download className="h-3.5 w-3.5" />
              <span>Export Redline</span>
            </button>

            <button
              type="button"
              onClick={() => {
                setAccepted(!accepted);
                showToast(accepted ? 'Changes unaccepted.' : 'Changes accepted and logged to dossier.');
              }}
              className={`inline-flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-semibold shadow-sm transition-all cursor-pointer ${
                accepted 
                  ? 'bg-emerald-600 hover:bg-emerald-700 text-white shadow-emerald-600/20' 
                  : 'bg-blue-600 hover:bg-blue-700 text-white shadow-blue-600/20'
              }`}
            >
              <CheckCircle2 className="h-3.5 w-3.5" />
              <span>{accepted ? 'Changes Accepted' : 'Accept Changes'}</span>
            </button>
          </div>
        </div>

        {/* View Mode Switcher: Matter Dossier vs Custom AI Compare */}
        <div className="flex items-center justify-between border-b border-slate-200/80 pb-3 dark:border-slate-800">
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={() => setActiveTab('redline')}
              className={`px-3 py-1.5 text-xs font-semibold rounded-lg transition-colors cursor-pointer ${
                activeTab === 'redline'
                  ? 'bg-white text-blue-700 shadow-2xs border border-slate-200 dark:bg-slate-800 dark:text-blue-300 dark:border-slate-700'
                  : 'text-slate-500 hover:text-slate-900 dark:text-slate-400 dark:hover:text-white'
              }`}
            >
              Dossier Redline (ARB-2024-918)
            </button>

            <button
              type="button"
              onClick={() => setActiveTab('custom')}
              className={`px-3 py-1.5 text-xs font-semibold rounded-lg transition-colors cursor-pointer flex items-center gap-1.5 ${
                activeTab === 'custom'
                  ? 'bg-white text-blue-700 shadow-2xs border border-slate-200 dark:bg-slate-800 dark:text-blue-300 dark:border-slate-700'
                  : 'text-slate-500 hover:text-slate-900 dark:text-slate-400 dark:hover:text-white'
              }`}
            >
              <Sparkles className="h-3 w-3 text-blue-600 dark:text-blue-400" />
              <span>Upload Custom Documents for AI Diff</span>
            </button>
          </div>
        </div>

        {activeTab === 'redline' ? (
          <>
            {/* Side-by-Side Comparison Panels */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 items-start">
              {/* Left Column: Original Agreement */}
              <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-2xs dark:border-slate-800 dark:bg-slate-900 flex flex-col gap-5">
                {/* Panel Header */}
                <div className="flex items-center justify-between border-b border-slate-100 pb-4 dark:border-slate-800">
                  <div className="flex items-center gap-2.5">
                    <History className="h-4 w-4 text-slate-400" />
                    <div>
                      <h2 className="text-sm font-bold text-slate-900 dark:text-white">
                        Original Agreement
                      </h2>
                      <p className="text-[11px] text-slate-400">
                        Baseline v1.1 • Sept 14, 2023
                      </p>
                    </div>
                  </div>
                  <span className="rounded-md bg-slate-100 px-2 py-0.5 text-[11px] font-medium text-slate-600 dark:bg-slate-800 dark:text-slate-300">
                    Baseline
                  </span>
                </div>

                {/* Section: PREAMBLE */}
                <div className="flex flex-col gap-1.5">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500">
                    PREAMBLE
                  </span>
                  <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed">
                    This Master Services Agreement is entered into by and between Alpha Vendor Corp (&quot;Provider&quot;) and Zenith Global Logistics (&quot;Client&quot;).
                  </p>
                </div>

                {/* Diff Box: CLAUSE 8 • PAYMENT TERMS */}
                <div className="rounded-xl border border-rose-200 bg-rose-50/40 p-4 dark:border-rose-900/60 dark:bg-rose-950/20 flex flex-col gap-2">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-1.5 text-rose-700 dark:text-rose-400 font-bold text-xs tracking-wide">
                      <MinusCircle className="h-3.5 w-3.5 text-rose-600 dark:text-rose-400" />
                      <span>CLAUSE 8 • PAYMENT TERMS</span>
                    </div>
                    <span className="rounded bg-rose-100/80 px-2 py-0.5 text-[10px] font-semibold text-rose-700 dark:bg-rose-900/60 dark:text-rose-300">
                      Replaced
                    </span>
                  </div>
                  <p className="text-xs text-rose-900/80 line-through decoration-rose-400 decoration-1 dark:text-rose-300 leading-relaxed font-sans">
                    &quot;All undisputed invoices rendered under this Agreement shall mature and be payable by Client strictly within thirty (30) business days from the receipt date thereof.&quot;
                  </p>
                </div>

                {/* Diff Box: CLAUSE 12 • JURISDICTION */}
                <div className="rounded-xl border border-amber-200 bg-amber-50/40 p-4 dark:border-amber-900/60 dark:bg-amber-950/20 flex flex-col gap-2">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-1.5 text-amber-800 dark:text-amber-300 font-bold text-xs tracking-wide">
                      <AlertTriangle className="h-3.5 w-3.5 text-amber-600 dark:text-amber-400" />
                      <span>CLAUSE 12 • JURISDICTION</span>
                    </div>
                    <span className="rounded bg-amber-100 px-2 py-0.5 text-[10px] font-semibold text-amber-800 dark:bg-amber-900/60 dark:text-amber-300">
                      Offshore Forum
                    </span>
                  </div>
                  <p className="text-xs text-amber-900/80 line-through decoration-amber-400 decoration-1 dark:text-amber-300 leading-relaxed font-sans">
                    &quot;Any unresolved dispute arising hereunder shall be finally resolved under the Arbitration Rules of the Singapore International Arbitration Centre (SIAC) by three arbitrators.&quot;
                  </p>
                </div>

                {/* Section: SECTION 19 */}
                <div className="flex flex-col gap-1.5">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500">
                    SECTION 19
                  </span>
                  <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed">
                    Standard Force Majeure terms covering acts of God, flood, war, civil commotion, or natural occurrences.
                  </p>
                </div>
              </div>

              {/* Right Column: Proposed Counter-Draft */}
              <div className="rounded-xl border border-blue-200 bg-white p-6 shadow-2xs dark:border-blue-900/60 dark:bg-slate-900 flex flex-col gap-5">
                {/* Panel Header */}
                <div className="flex items-center justify-between border-b border-slate-100 pb-4 dark:border-slate-800">
                  <div className="flex items-center gap-2.5">
                    <FileEdit className="h-4 w-4 text-blue-600 dark:text-blue-400" />
                    <div>
                      <h2 className="text-sm font-bold text-slate-900 dark:text-white">
                        Proposed Counter-Draft
                      </h2>
                      <p className="text-[11px] font-medium text-blue-600 dark:text-blue-400">
                        Client Counter v2.0 • Oct 28, 2023
                      </p>
                    </div>
                  </div>
                  <span className="rounded-md bg-blue-100 px-2 py-0.5 text-[11px] font-semibold text-blue-700 dark:bg-blue-950 dark:text-blue-300">
                    Proposed
                  </span>
                </div>

                {/* Section: PREAMBLE */}
                <div className="flex flex-col gap-1.5">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500">
                    PREAMBLE
                  </span>
                  <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed">
                    This Master Services Agreement is entered into by and between Alpha Vendor Corp (&quot;Provider&quot;) and Zenith Global Logistics (&quot;Client&quot;).
                  </p>
                </div>

                {/* Diff Box: CLAUSE 8 • PAYMENT TERMS */}
                <div className="rounded-xl border border-blue-100 bg-white p-4 shadow-2xs dark:border-slate-800 dark:bg-slate-800/60 flex flex-col gap-2">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-1.5 text-blue-700 dark:text-blue-400 font-bold text-xs tracking-wide">
                      <FileText className="h-3.5 w-3.5 text-blue-600 dark:text-blue-400" />
                      <span>CLAUSE 8 • PAYMENT TERMS</span>
                    </div>
                    <span className="rounded border border-rose-200 bg-rose-50 px-2 py-0.5 text-[10px] font-bold text-rose-700 dark:border-rose-900/60 dark:bg-rose-950/60 dark:text-rose-300">
                      Net 30 → Net 90
                    </span>
                  </div>
                  <p className="text-xs text-slate-700 dark:text-slate-200 leading-relaxed">
                    &quot;All undisputed invoices rendered under this Agreement shall mature and be payable by Client strictly within{' '}
                    <mark className="rounded bg-amber-100 px-1 py-0.5 font-bold text-amber-900 dark:bg-amber-950 dark:text-amber-200">
                      ninety (90) calendar days
                    </mark>{' '}
                    from verification of satisfactory delivery milestones.&quot;
                  </p>
                </div>

                {/* Diff Box: CLAUSE 12 • JURISDICTION */}
                <div className="rounded-xl border border-blue-100 bg-white p-4 shadow-2xs dark:border-slate-800 dark:bg-slate-800/60 flex flex-col gap-2">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-1.5 text-blue-700 dark:text-blue-400 font-bold text-xs tracking-wide">
                      <Scale className="h-3.5 w-3.5 text-blue-600 dark:text-blue-400" />
                      <span>CLAUSE 12 • JURISDICTION</span>
                    </div>
                    <span className="rounded border border-blue-200 bg-blue-50 px-2 py-0.5 text-[10px] font-semibold text-blue-700 dark:border-blue-900 dark:bg-blue-950 dark:text-blue-300">
                      Seat: Mumbai
                    </span>
                  </div>
                  <p className="text-xs text-slate-700 dark:text-slate-200 leading-relaxed">
                    &quot;Disputes shall be resolved exclusively through{' '}
                    <mark className="rounded bg-blue-100 px-1 py-0.5 font-bold text-blue-900 dark:bg-blue-950 dark:text-blue-200">
                      arbitration seated in Mumbai, India
                    </mark>{' '}
                    governed by the Arbitration and Conciliation Act 1996, conducted in English.&quot;
                  </p>
                </div>

                {/* Section: SECTION 19 */}
                <div className="flex flex-col gap-1.5">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500">
                    SECTION 19
                  </span>
                  <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed">
                    Expands Force Majeure protections to include explicit regulatory shutdowns and sovereign embargoes.
                  </p>
                </div>
              </div>
            </div>

            {/* Critical Divergences Section */}
            <section className="flex flex-col gap-4 mt-4">
              <h2 className="text-[11px] font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500">
                CRITICAL DIVERGENCES
              </h2>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Impact Card 1: Payment Terms */}
                <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-2xs dark:border-slate-800 dark:bg-slate-900 flex flex-col justify-between">
                  <div>
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <span className="h-2 w-2 rounded-full bg-rose-500" />
                        <h3 className="text-sm font-bold text-slate-900 dark:text-white">
                          Payment Terms
                        </h3>
                      </div>
                      <span className="rounded-full border border-rose-100 bg-rose-50 px-2 py-0.5 text-[10px] font-bold text-rose-700 uppercase tracking-wider dark:border-rose-900/60 dark:bg-rose-950/60 dark:text-rose-300">
                        HIGH IMPACT
                      </span>
                    </div>

                    <h4 className="mt-3 text-sm font-semibold text-slate-900 dark:text-slate-100">
                      Extended from 30 to 90 days
                    </h4>
                    <p className="mt-1.5 text-xs text-slate-500 dark:text-slate-400 leading-relaxed">
                      Substantially slows operational cash flow and forces self-financing of provider deliverables for up to three full billing cycles.
                    </p>
                  </div>

                  <div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-3 dark:border-slate-800 text-xs">
                    <span className="text-slate-400">
                      Recommendation: Reject extension
                    </span>
                    <button
                      type="button"
                      onClick={() => {
                        setCounterProposed(true);
                        showToast('Counter-proposal "Net 45" prepared and copied to clipboard.');
                      }}
                      className="font-semibold text-blue-600 hover:text-blue-700 flex items-center gap-1 dark:text-blue-400 dark:hover:text-blue-300 cursor-pointer"
                    >
                      <span>{counterProposed ? '✓ Counter-Proposed (Net 45)' : 'Propose Net 45'}</span>
                      <ArrowRight className="h-3 w-3" />
                    </button>
                  </div>
                </div>

                {/* Impact Card 2: Arbitration Venue */}
                <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-2xs dark:border-slate-800 dark:bg-slate-900 flex flex-col justify-between">
                  <div>
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <span className="h-2 w-2 rounded-full bg-amber-500" />
                        <h3 className="text-sm font-bold text-slate-900 dark:text-white">
                          Arbitration Venue
                        </h3>
                      </div>
                      <span className="rounded-full border border-amber-100 bg-amber-50 px-2 py-0.5 text-[10px] font-bold text-amber-700 uppercase tracking-wider dark:border-amber-900/60 dark:bg-amber-950/60 dark:text-amber-300">
                        MEDIUM IMPACT
                      </span>
                    </div>

                    <h4 className="mt-3 text-sm font-semibold text-slate-900 dark:text-slate-100">
                      Changed to Domestic Court (Mumbai)
                    </h4>
                    <p className="mt-1.5 text-xs text-slate-500 dark:text-slate-400 leading-relaxed">
                      Replaces expedited neutral SIAC Singapore proceedings with domestic statutory framework under the Arbitration and Conciliation Act.
                    </p>
                  </div>

                  <div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-3 dark:border-slate-800 text-xs">
                    <span className="text-slate-400">
                      Recommendation: Counter seat
                    </span>
                    <button
                      type="button"
                      onClick={() => {
                        showToast('Counter seat proposal generated for New Delhi International Arbitration Centre.');
                      }}
                      className="font-semibold text-blue-600 hover:text-blue-700 flex items-center gap-1 dark:text-blue-400 dark:hover:text-blue-300 cursor-pointer"
                    >
                      <span>Counter Proposal</span>
                      <ArrowRight className="h-3 w-3" />
                    </button>
                  </div>
                </div>
              </div>
            </section>
          </>
        ) : (
          /* Custom AI Compare View */
          <div className="flex flex-col gap-6">
            <form onSubmit={handleCustomCompare} className="space-y-6">
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <div>
                  <label htmlFor="custom-doc-type" className="mb-1 block text-xs font-semibold text-slate-700 dark:text-slate-300">
                    Agreement Type
                  </label>
                  <select
                    id="custom-doc-type"
                    value={docType}
                    onChange={(e) => setDocType(e.target.value as DocumentType)}
                    className="w-full rounded-xl border border-slate-300 bg-white px-3.5 py-2.5 text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-500 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                  >
                    {DOCUMENT_TYPES.map((t) => (
                      <option key={t} value={t}>{DOCUMENT_TYPE_LABELS[t]}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label htmlFor="custom-lang" className="mb-1 block text-xs font-semibold text-slate-700 dark:text-slate-300">
                    Explanation Language
                  </label>
                  <select
                    id="custom-lang"
                    value={language}
                    onChange={(e) => setLanguage(e.target.value as OutputLanguage)}
                    className="w-full rounded-xl border border-slate-300 bg-white px-3.5 py-2.5 text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-500 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                  >
                    {OUTPUT_LANGUAGES.map((c) => (
                      <option key={c} value={c}>{LANGUAGE_LABELS[c]}</option>
                    ))}
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
                <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-2xs dark:border-slate-800 dark:bg-slate-900">
                  <label htmlFor="custom-doc-a" className="mb-2 block text-xs font-bold text-slate-900 dark:text-white">
                    Original Agreement (Doc A)
                  </label>
                  <textarea
                    id="custom-doc-a"
                    value={docAText}
                    onChange={(e) => setDocAText(e.target.value)}
                    placeholder="Paste original contract text here…"
                    rows={8}
                    className="w-full rounded-lg border border-slate-200 p-3 text-xs text-slate-800 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                  />
                </div>

                <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-2xs dark:border-slate-800 dark:bg-slate-900">
                  <label htmlFor="custom-doc-b" className="mb-2 block text-xs font-bold text-slate-900 dark:text-white">
                    Counter-Draft / Revised Agreement (Doc B)
                  </label>
                  <textarea
                    id="custom-doc-b"
                    value={docBText}
                    onChange={(e) => setDocBText(e.target.value)}
                    placeholder="Paste revised contract text here…"
                    rows={8}
                    className="w-full rounded-lg border border-slate-200 p-3 text-xs text-slate-800 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                  />
                </div>
              </div>

              {customError && (
                <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-xs font-medium text-red-700 dark:border-red-900/50 dark:bg-red-950/40 dark:text-red-300">
                  {customError}
                </div>
              )}

              <button
                type="submit"
                disabled={isLoading || !docAText.trim() || !docBText.trim()}
                className="w-full rounded-xl bg-blue-600 hover:bg-blue-700 px-6 py-3 text-xs font-semibold text-white shadow-sm transition-all disabled:opacity-50 cursor-pointer"
              >
                {isLoading ? 'Comparing with Gemini AI…' : 'Run AI Comparison'}
              </button>
            </form>

            {/* Custom Comparison Results */}
            {customResult && (
              <div className="space-y-4 pt-4 border-t border-slate-200 dark:border-slate-800">
                <div className="rounded-xl border border-blue-200 bg-blue-50/70 p-5 dark:border-blue-900/50 dark:bg-blue-950/30">
                  <h3 className="font-bold text-blue-950 dark:text-blue-200 text-sm">
                    Executive Summary of Differences
                  </h3>
                  <p className="mt-1 text-xs text-blue-900 dark:text-blue-300 leading-relaxed">
                    {customResult.summary}
                  </p>
                </div>

                <div className="space-y-3">
                  {customResult.items.map((item, idx) => (
                    <div key={idx} className="rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900 text-xs">
                      <div className="flex items-center justify-between border-b border-slate-100 pb-2 dark:border-slate-800">
                        <span className="font-bold text-slate-900 dark:text-white">{item.topic}</span>
                        <span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-semibold text-slate-600 dark:bg-slate-800 dark:text-slate-300">
                          {item.riskChange}
                        </span>
                      </div>
                      <div className="mt-2 grid grid-cols-1 sm:grid-cols-2 gap-3 text-[11px]">
                        <div className="bg-slate-50 p-2.5 rounded dark:bg-slate-800/60">
                          <span className="font-bold text-slate-500">Doc A: </span>
                          <span className="text-slate-700 dark:text-slate-300">{item.inDocA ?? 'Not stated'}</span>
                        </div>
                        <div className="bg-slate-50 p-2.5 rounded dark:bg-slate-800/60">
                          <span className="font-bold text-slate-500">Doc B: </span>
                          <span className="text-slate-700 dark:text-slate-300">{item.inDocB ?? 'Not stated'}</span>
                        </div>
                      </div>
                      <p className="mt-2 text-slate-600 dark:text-slate-400">
                        <span className="font-bold">Key Difference: </span>
                        {item.difference}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        {/* Footer Disclaimer */}
        <footer className="mt-8 border-t border-slate-100 pt-6 dark:border-slate-800">
          <Disclaimer variant="footer" />
        </footer>
      </main>
    </div>
  );
}
